[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Cassandra Cole", email = "smac1@uab.edu"},
]
dependencies = [
]
requires-python = ">=3.10"
license = {text = "MIT"}
